### ISSUE TITLE
Not an issue, just a question

### ISSUE THREAD

**Issue by Dhrhciebcy** [sschaub/metz-project#1]
Hi, as the title says, I do not report problems in the project, I just wanted to ask how you generated the CODM file to create the extension.
Did you do it "by hand"? Or have you used a program?
Thank you
Andry

**Comment by sschaub** [comment]
I did it "by hand." It's been so long that I can't remember the details, but I think I used an XML editor.

**Comment by Dhrhciebcy** [comment]
I understand, thank you very much!
